// Generated by scripts/commands/build-apps-script-config.mjs. Do not edit manually.
var SITCON_PHOTO_FINDER_CONFIG = {
  "generatedAt": "not recorded in committed source",
  "schemaVersion": "2026-1.0.0",
  "taxonomyVersion": "sha256:4ee45762f300",
  "sponsorshipItemsVersion": "sha256:e33bfe6034e1",
  "sponsorshipItemsSnapshotNote": "SITCON 2026 CFS has ended. Treat this file as a fixed snapshot; future CFS versions should replace or extend it explicitly instead of being automatically synced.",
  "photosSheetName": "photos",
  "taxonomySheetName": "taxonomy",
  "schemaMetaSheetName": "schema_meta",
  "headers": [
    "photo_id",
    "photo_url",
    "album_ids",
    "image_preview_url",
    "album_title",
    "event_name",
    "event_year",
    "people_count",
    "subject_type",
    "photographer",
    "license",
    "scene_tags",
    "mood_tags",
    "recommended_uses",
    "sponsorship_items",
    "sponsorship_tags",
    "orientation",
    "has_negative_space",
    "safe_crop",
    "visual_description",
    "public_use_status",
    "priority_level",
    "collections",
    "curation_notes",
    "curation_status"
  ],
  "fields": [
    {
      "name": "photo_id",
      "labelZh": "Flickr 照片 ID",
      "type": "string",
      "required": true,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "Flickr 照片 ID，用來避免重複匯入。"
    },
    {
      "name": "photo_url",
      "labelZh": "Flickr 公開頁面",
      "type": "url",
      "required": true,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "Flickr 公開頁面，用來回到原始照片確認脈絡。"
    },
    {
      "name": "album_ids",
      "labelZh": "來源相簿 ID",
      "type": "string",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "",
      "descriptionZh": "這張照片曾由哪些 Flickr 相簿匯入或關聯。多值以分號分隔。"
    },
    {
      "name": "image_preview_url",
      "labelZh": "縮圖 URL",
      "type": "url",
      "required": true,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "搜尋介面顯示用縮圖。"
    },
    {
      "name": "album_title",
      "labelZh": "相簿名稱",
      "type": "string",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "Flickr 相簿名稱。若工具暫時抓不到，可以留空。"
    },
    {
      "name": "event_name",
      "labelZh": "活動名稱",
      "type": "string",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "例如 SITCON 年會、SITCON Camp。不確定就留空。"
    },
    {
      "name": "event_year",
      "labelZh": "活動年份",
      "type": "year",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "四位年份，例如 2026。"
    },
    {
      "name": "people_count",
      "labelZh": "照片中的人數",
      "type": "integer",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "照片中可辨識的人數估計值。可留空；若無人可填 0，值必須是非負整數。"
    },
    {
      "name": "subject_type",
      "labelZh": "主要視覺主體",
      "type": "taxonomy",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "subject_type",
      "descriptionZh": "照片海初篩用的主要視覺主體粗分類，例如人物、物件、餐食茶點、文字標示、螢幕或空間。只描述主體種類，不描述活動場景、人數規模或用途。"
    },
    {
      "name": "photographer",
      "labelZh": "攝影師署名",
      "type": "string",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "攝影師署名。SITCON 是 Flickr 帳號擁有者，不等於攝影師。"
    },
    {
      "name": "license",
      "labelZh": "授權資訊",
      "type": "string",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "Flickr 顯示的授權資訊。不確定時留空並使用 needs_review。"
    },
    {
      "name": "scene_tags",
      "labelZh": "場景標籤",
      "type": "taxonomy",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "scene_tags",
      "descriptionZh": "照片中看見的事實，例如攤位、會眾、舞台。"
    },
    {
      "name": "mood_tags",
      "labelZh": "氛圍標籤",
      "type": "taxonomy",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "mood_tags",
      "descriptionZh": "照片帶來的感受，例如熱鬧、專注、青春感。"
    },
    {
      "name": "recommended_uses",
      "labelZh": "建議用途",
      "type": "taxonomy",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "recommended_uses",
      "descriptionZh": "適合的工作用途，例如社群貼文、贊助提案。"
    },
    {
      "name": "sponsorship_items",
      "labelZh": "贊助品項",
      "type": "taxonomy",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "sponsorship_items",
      "descriptionZh": "對應 CFS 贊助品項，必須對齊 data/sponsorship-items.json。"
    },
    {
      "name": "sponsorship_tags",
      "labelZh": "贊助價值",
      "type": "taxonomy",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "sponsorship_tags",
      "descriptionZh": "贊助價值或佐證用途，例如品牌露出、會眾互動。"
    },
    {
      "name": "orientation",
      "labelZh": "照片方向",
      "type": "taxonomy",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "orientation",
      "descriptionZh": "landscape、portrait、square。"
    },
    {
      "name": "has_negative_space",
      "labelZh": "是否有留白",
      "type": "boolean",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "true 或 false，表示是否有明顯留白可放字。"
    },
    {
      "name": "safe_crop",
      "labelZh": "安全裁切比例",
      "type": "taxonomy",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "safe_crop",
      "descriptionZh": "適合裁切的比例，例如 1:1、16:9。"
    },
    {
      "name": "visual_description",
      "labelZh": "畫面描述",
      "type": "text",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "1 到 2 句中立的可見畫面描述，用於自然語言找圖輔助。只描述照片中看得到的物件、動作、文字、位置與空間關係，不自行補活動名稱、年份、身份、單位或贊助推論。"
    },
    {
      "name": "public_use_status",
      "labelZh": "公開使用狀態",
      "type": "taxonomy",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "public_use_status",
      "descriptionZh": "approved、needs_review、avoid。不確定用 needs_review。"
    },
    {
      "name": "priority_level",
      "labelZh": "推薦優先度",
      "type": "taxonomy",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "priority_level",
      "descriptionZh": "high、normal、low。表示推薦使用優先度，不是照片品質分數。"
    },
    {
      "name": "collections",
      "labelZh": "素材包",
      "type": "string",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "",
      "descriptionZh": "素材包，例如志工招募、贊助提案、網站視覺。"
    },
    {
      "name": "curation_notes",
      "labelZh": "整理備註",
      "type": "text",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "公開 repo 與正式 Sheets 中仍視為公開資料，不要寫入敏感內部資訊。"
    },
    {
      "name": "curation_status",
      "labelZh": "整理狀態",
      "type": "taxonomy",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "curation_status",
      "descriptionZh": "unreviewed、ai_labeled、reviewed。精選或封存不放在整理狀態；優先推薦用 priority_level 或 collections，避免推薦用 public_use_status = avoid。"
    }
  ],
  "reviewedRequiredFields": [
    "subject_type",
    "scene_tags"
  ],
  "taxonomy": {
    "scene_tags": [
      "講者",
      "會眾",
      "報到",
      "攤位",
      "工作人員",
      "合照",
      "交流",
      "舞台",
      "背板",
      "茶點",
      "手作",
      "工作坊",
      "排隊",
      "休息區",
      "直播",
      "攝影",
      "指標",
      "場地",
      "螢幕",
      "頒獎",
      "兒童"
    ],
    "subject_type": [
      "people",
      "object",
      "food",
      "text_signage",
      "screen",
      "space"
    ],
    "mood_tags": [
      "熱鬧",
      "專注",
      "溫暖",
      "青春感",
      "專業",
      "幕後感",
      "友善",
      "交流感",
      "成就感",
      "儀式感",
      "活力",
      "安靜"
    ],
    "recommended_uses": [
      "社群貼文",
      "網站 hero",
      "志工招募",
      "投稿宣傳",
      "報名宣傳",
      "贊助提案",
      "贊助成果報告",
      "新聞稿",
      "活動回顧",
      "社群介紹",
      "講者宣傳",
      "簡報"
    ],
    "sponsorship_items": [
      "Badge 繩廠商 Logo 曝光",
      "年會 T-shirt Logo 曝光",
      "獨家帆布袋",
      "獨家導遊團行程",
      "會議室椅套曝光",
      "午餐旗、點心旗",
      "獨家議程",
      "遠距會議室議程",
      "SITCON 貼紙置入",
      "年會開閉幕口播",
      "一次性紙餐墊",
      "拍貼機贊助商方案",
      "SITCON 會場指標置入",
      "會場攤位加大",
      "樓梯打卡牆",
      "洗手間標語曝光",
      "接駁車車內廣播",
      "入口落地窗背板 Logo 曝光",
      "會場電視輪播",
      "會場攤位",
      "SITCON 網站議程表置入",
      "SITCON 與會者 Email 推播置入",
      "工作人員徽章曝光",
      "明信片",
      "面紙包",
      "年會意象背板",
      "網路宣傳",
      "「遠道而來票」獨家冠名",
      "OPass App 推播公告",
      "樓梯欄杆垂掛布條展出",
      "R0 影片輪播",
      "R0 影片輪播加時",
      "議程廳講者背板",
      "R0 議程前夥伴宣讀",
      "錄影模板  Logo 曝光",
      "迎賓袋文宣",
      "網頁 Logo 曝光",
      "年會共筆 Logo 曝光",
      "門口議程表 Logo 曝光",
      "贈票"
    ],
    "sponsorship_tags": [
      "攤位曝光",
      "品牌露出",
      "會眾互動",
      "實體導流",
      "主舞台曝光",
      "議程曝光",
      "線上曝光",
      "參與者體驗",
      "贊助成果佐證",
      "觸及學生族群",
      "社群信任感",
      "合作夥伴形象"
    ],
    "orientation": [
      "landscape",
      "portrait",
      "square"
    ],
    "safe_crop": [
      "1:1",
      "16:9",
      "9:16"
    ],
    "public_use_status": [
      "approved",
      "needs_review",
      "avoid"
    ],
    "priority_level": [
      "high",
      "normal",
      "low"
    ],
    "curation_status": [
      "unreviewed",
      "ai_labeled",
      "reviewed"
    ],
    "option_labels": {
      "subject_type": {
        "people": "人物",
        "object": "物件",
        "food": "餐食茶點",
        "text_signage": "文字標示",
        "screen": "螢幕",
        "space": "空間"
      },
      "orientation": {
        "landscape": "橫式",
        "portrait": "直式",
        "square": "方形"
      },
      "public_use_status": {
        "approved": "已確認",
        "needs_review": "待整理確認",
        "avoid": "不建議"
      },
      "priority_level": {
        "high": "優先推薦",
        "normal": "一般候選",
        "low": "低優先"
      },
      "curation_status": {
        "unreviewed": "未整理",
        "ai_labeled": "AI 初標",
        "reviewed": "已整理"
      },
      "recommended_uses": {
        "社群貼文": "社群貼文",
        "網站 hero": "網站視覺",
        "志工招募": "志工招募",
        "投稿宣傳": "投稿宣傳",
        "報名宣傳": "報名宣傳",
        "贊助提案": "贊助提案",
        "贊助成果報告": "贊助成果",
        "新聞稿": "新聞稿",
        "活動回顧": "活動回顧",
        "社群介紹": "社群介紹",
        "講者宣傳": "講者宣傳",
        "簡報": "簡報"
      },
      "has_negative_space": {
        "true": "有留白",
        "false": "無明顯留白"
      }
    },
    "sponsorship_item_categories": [
      "打包專屬",
      "數位媒體曝光",
      "更多曝光方式",
      "獨家議程",
      "現場實體曝光",
      "紀念品配件曝光"
    ]
  },
  "taxonomySheet": {
    "headers": [
      "taxonomy_key",
      "value",
      "label_zh",
      "order"
    ],
    "rows": [
      {
        "taxonomy_key": "scene_tags",
        "value": "講者",
        "label_zh": "講者",
        "order": "1"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "會眾",
        "label_zh": "會眾",
        "order": "2"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "報到",
        "label_zh": "報到",
        "order": "3"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "攤位",
        "label_zh": "攤位",
        "order": "4"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "工作人員",
        "label_zh": "工作人員",
        "order": "5"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "合照",
        "label_zh": "合照",
        "order": "6"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "交流",
        "label_zh": "交流",
        "order": "7"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "舞台",
        "label_zh": "舞台",
        "order": "8"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "背板",
        "label_zh": "背板",
        "order": "9"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "茶點",
        "label_zh": "茶點",
        "order": "10"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "手作",
        "label_zh": "手作",
        "order": "11"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "工作坊",
        "label_zh": "工作坊",
        "order": "12"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "排隊",
        "label_zh": "排隊",
        "order": "13"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "休息區",
        "label_zh": "休息區",
        "order": "14"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "直播",
        "label_zh": "直播",
        "order": "15"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "攝影",
        "label_zh": "攝影",
        "order": "16"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "指標",
        "label_zh": "指標",
        "order": "17"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "場地",
        "label_zh": "場地",
        "order": "18"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "螢幕",
        "label_zh": "螢幕",
        "order": "19"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "頒獎",
        "label_zh": "頒獎",
        "order": "20"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "兒童",
        "label_zh": "兒童",
        "order": "21"
      },
      {
        "taxonomy_key": "subject_type",
        "value": "people",
        "label_zh": "人物",
        "order": "1"
      },
      {
        "taxonomy_key": "subject_type",
        "value": "object",
        "label_zh": "物件",
        "order": "2"
      },
      {
        "taxonomy_key": "subject_type",
        "value": "food",
        "label_zh": "餐食茶點",
        "order": "3"
      },
      {
        "taxonomy_key": "subject_type",
        "value": "text_signage",
        "label_zh": "文字標示",
        "order": "4"
      },
      {
        "taxonomy_key": "subject_type",
        "value": "screen",
        "label_zh": "螢幕",
        "order": "5"
      },
      {
        "taxonomy_key": "subject_type",
        "value": "space",
        "label_zh": "空間",
        "order": "6"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "熱鬧",
        "label_zh": "熱鬧",
        "order": "1"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "專注",
        "label_zh": "專注",
        "order": "2"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "溫暖",
        "label_zh": "溫暖",
        "order": "3"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "青春感",
        "label_zh": "青春感",
        "order": "4"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "專業",
        "label_zh": "專業",
        "order": "5"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "幕後感",
        "label_zh": "幕後感",
        "order": "6"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "友善",
        "label_zh": "友善",
        "order": "7"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "交流感",
        "label_zh": "交流感",
        "order": "8"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "成就感",
        "label_zh": "成就感",
        "order": "9"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "儀式感",
        "label_zh": "儀式感",
        "order": "10"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "活力",
        "label_zh": "活力",
        "order": "11"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "安靜",
        "label_zh": "安靜",
        "order": "12"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "社群貼文",
        "label_zh": "社群貼文",
        "order": "1"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "網站 hero",
        "label_zh": "網站視覺",
        "order": "2"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "志工招募",
        "label_zh": "志工招募",
        "order": "3"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "投稿宣傳",
        "label_zh": "投稿宣傳",
        "order": "4"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "報名宣傳",
        "label_zh": "報名宣傳",
        "order": "5"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "贊助提案",
        "label_zh": "贊助提案",
        "order": "6"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "贊助成果報告",
        "label_zh": "贊助成果",
        "order": "7"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "新聞稿",
        "label_zh": "新聞稿",
        "order": "8"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "活動回顧",
        "label_zh": "活動回顧",
        "order": "9"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "社群介紹",
        "label_zh": "社群介紹",
        "order": "10"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "講者宣傳",
        "label_zh": "講者宣傳",
        "order": "11"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "簡報",
        "label_zh": "簡報",
        "order": "12"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "Badge 繩廠商 Logo 曝光",
        "label_zh": "Badge 繩廠商 Logo 曝光",
        "order": "1"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "年會 T-shirt Logo 曝光",
        "label_zh": "年會 T-shirt Logo 曝光",
        "order": "2"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "獨家帆布袋",
        "label_zh": "獨家帆布袋",
        "order": "3"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "獨家導遊團行程",
        "label_zh": "獨家導遊團行程",
        "order": "4"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "會議室椅套曝光",
        "label_zh": "會議室椅套曝光",
        "order": "5"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "午餐旗、點心旗",
        "label_zh": "午餐旗、點心旗",
        "order": "6"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "獨家議程",
        "label_zh": "獨家議程",
        "order": "7"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "遠距會議室議程",
        "label_zh": "遠距會議室議程",
        "order": "8"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "SITCON 貼紙置入",
        "label_zh": "SITCON 貼紙置入",
        "order": "9"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "年會開閉幕口播",
        "label_zh": "年會開閉幕口播",
        "order": "10"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "一次性紙餐墊",
        "label_zh": "一次性紙餐墊",
        "order": "11"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "拍貼機贊助商方案",
        "label_zh": "拍貼機贊助商方案",
        "order": "12"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "SITCON 會場指標置入",
        "label_zh": "SITCON 會場指標置入",
        "order": "13"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "會場攤位加大",
        "label_zh": "會場攤位加大",
        "order": "14"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "樓梯打卡牆",
        "label_zh": "樓梯打卡牆",
        "order": "15"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "洗手間標語曝光",
        "label_zh": "洗手間標語曝光",
        "order": "16"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "接駁車車內廣播",
        "label_zh": "接駁車車內廣播",
        "order": "17"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "入口落地窗背板 Logo 曝光",
        "label_zh": "入口落地窗背板 Logo 曝光",
        "order": "18"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "會場電視輪播",
        "label_zh": "會場電視輪播",
        "order": "19"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "會場攤位",
        "label_zh": "會場攤位",
        "order": "20"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "SITCON 網站議程表置入",
        "label_zh": "SITCON 網站議程表置入",
        "order": "21"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "SITCON 與會者 Email 推播置入",
        "label_zh": "SITCON 與會者 Email 推播置入",
        "order": "22"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "工作人員徽章曝光",
        "label_zh": "工作人員徽章曝光",
        "order": "23"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "明信片",
        "label_zh": "明信片",
        "order": "24"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "面紙包",
        "label_zh": "面紙包",
        "order": "25"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "年會意象背板",
        "label_zh": "年會意象背板",
        "order": "26"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "網路宣傳",
        "label_zh": "網路宣傳",
        "order": "27"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "「遠道而來票」獨家冠名",
        "label_zh": "「遠道而來票」獨家冠名",
        "order": "28"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "OPass App 推播公告",
        "label_zh": "OPass App 推播公告",
        "order": "29"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "樓梯欄杆垂掛布條展出",
        "label_zh": "樓梯欄杆垂掛布條展出",
        "order": "30"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "R0 影片輪播",
        "label_zh": "R0 影片輪播",
        "order": "31"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "R0 影片輪播加時",
        "label_zh": "R0 影片輪播加時",
        "order": "32"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "議程廳講者背板",
        "label_zh": "議程廳講者背板",
        "order": "33"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "R0 議程前夥伴宣讀",
        "label_zh": "R0 議程前夥伴宣讀",
        "order": "34"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "錄影模板  Logo 曝光",
        "label_zh": "錄影模板  Logo 曝光",
        "order": "35"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "迎賓袋文宣",
        "label_zh": "迎賓袋文宣",
        "order": "36"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "網頁 Logo 曝光",
        "label_zh": "網頁 Logo 曝光",
        "order": "37"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "年會共筆 Logo 曝光",
        "label_zh": "年會共筆 Logo 曝光",
        "order": "38"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "門口議程表 Logo 曝光",
        "label_zh": "門口議程表 Logo 曝光",
        "order": "39"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "贈票",
        "label_zh": "贈票",
        "order": "40"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "攤位曝光",
        "label_zh": "攤位曝光",
        "order": "1"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "品牌露出",
        "label_zh": "品牌露出",
        "order": "2"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "會眾互動",
        "label_zh": "會眾互動",
        "order": "3"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "實體導流",
        "label_zh": "實體導流",
        "order": "4"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "主舞台曝光",
        "label_zh": "主舞台曝光",
        "order": "5"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "議程曝光",
        "label_zh": "議程曝光",
        "order": "6"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "線上曝光",
        "label_zh": "線上曝光",
        "order": "7"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "參與者體驗",
        "label_zh": "參與者體驗",
        "order": "8"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "贊助成果佐證",
        "label_zh": "贊助成果佐證",
        "order": "9"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "觸及學生族群",
        "label_zh": "觸及學生族群",
        "order": "10"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "社群信任感",
        "label_zh": "社群信任感",
        "order": "11"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "合作夥伴形象",
        "label_zh": "合作夥伴形象",
        "order": "12"
      },
      {
        "taxonomy_key": "orientation",
        "value": "landscape",
        "label_zh": "橫式",
        "order": "1"
      },
      {
        "taxonomy_key": "orientation",
        "value": "portrait",
        "label_zh": "直式",
        "order": "2"
      },
      {
        "taxonomy_key": "orientation",
        "value": "square",
        "label_zh": "方形",
        "order": "3"
      },
      {
        "taxonomy_key": "safe_crop",
        "value": "1:1",
        "label_zh": "1:1",
        "order": "1"
      },
      {
        "taxonomy_key": "safe_crop",
        "value": "16:9",
        "label_zh": "16:9",
        "order": "2"
      },
      {
        "taxonomy_key": "safe_crop",
        "value": "9:16",
        "label_zh": "9:16",
        "order": "3"
      },
      {
        "taxonomy_key": "public_use_status",
        "value": "approved",
        "label_zh": "已確認",
        "order": "1"
      },
      {
        "taxonomy_key": "public_use_status",
        "value": "needs_review",
        "label_zh": "待整理確認",
        "order": "2"
      },
      {
        "taxonomy_key": "public_use_status",
        "value": "avoid",
        "label_zh": "不建議",
        "order": "3"
      },
      {
        "taxonomy_key": "priority_level",
        "value": "high",
        "label_zh": "優先推薦",
        "order": "1"
      },
      {
        "taxonomy_key": "priority_level",
        "value": "normal",
        "label_zh": "一般候選",
        "order": "2"
      },
      {
        "taxonomy_key": "priority_level",
        "value": "low",
        "label_zh": "低優先",
        "order": "3"
      },
      {
        "taxonomy_key": "curation_status",
        "value": "unreviewed",
        "label_zh": "未整理",
        "order": "1"
      },
      {
        "taxonomy_key": "curation_status",
        "value": "ai_labeled",
        "label_zh": "AI 初標",
        "order": "2"
      },
      {
        "taxonomy_key": "curation_status",
        "value": "reviewed",
        "label_zh": "已整理",
        "order": "3"
      },
      {
        "taxonomy_key": "sponsorship_item_categories",
        "value": "打包專屬",
        "label_zh": "打包專屬",
        "order": "1"
      },
      {
        "taxonomy_key": "sponsorship_item_categories",
        "value": "數位媒體曝光",
        "label_zh": "數位媒體曝光",
        "order": "2"
      },
      {
        "taxonomy_key": "sponsorship_item_categories",
        "value": "更多曝光方式",
        "label_zh": "更多曝光方式",
        "order": "3"
      },
      {
        "taxonomy_key": "sponsorship_item_categories",
        "value": "獨家議程",
        "label_zh": "獨家議程",
        "order": "4"
      },
      {
        "taxonomy_key": "sponsorship_item_categories",
        "value": "現場實體曝光",
        "label_zh": "現場實體曝光",
        "order": "5"
      },
      {
        "taxonomy_key": "sponsorship_item_categories",
        "value": "紀念品配件曝光",
        "label_zh": "紀念品配件曝光",
        "order": "6"
      }
    ]
  },
  "validationMessages": {
    "completionRequired": "完成審核需要填寫此欄位",
    "completionWarning": "完成審核前需填寫",
    "duplicateListPrefix": "不可重複填寫：",
    "invalidBoolean": "必須是 true 或 false",
    "invalidInteger": "必須是非負整數",
    "invalidUrl": "必須是 http 或 https URL",
    "invalidYear": "必須是四位數年份",
    "required": "必填欄位不可空白",
    "unknownTaxonomyPrefix": "未知受控字彙："
  }
};
