// Generated by scripts/commands/build-apps-script-config.mjs. Do not edit manually.
var SITCON_PHOTO_FINDER_CONFIG = {
  "generatedAt": "not recorded in committed source",
  "schemaVersion": "2026-1.0.0",
  "taxonomyVersion": "sha256:e238f9a83700",
  "sponsorshipItemsVersion": "sha256:e33bfe6034e1",
  "sponsorshipItemsSnapshotNote": "SITCON 2026 CFS has ended. Treat this file as a fixed snapshot; future CFS versions should replace or extend it explicitly instead of being automatically synced.",
  "photosSheetName": "photos",
  "taxonomySheetName": "taxonomy",
  "schemaMetaSheetName": "schema_meta",
  "headers": [
    "photo_id",
    "photo_url",
    "album_ids",
    "image_preview_url",
    "album_title",
    "event_name",
    "event_year",
    "people_count",
    "subject_type",
    "photographer",
    "license",
    "scene_tags",
    "mood_tags",
    "recommended_uses",
    "sponsorship_items",
    "sponsorship_tags",
    "orientation",
    "has_negative_space",
    "safe_crop",
    "visual_description",
    "public_use_status",
    "priority_level",
    "collections",
    "curation_notes",
    "curation_status"
  ],
  "fields": [
    {
      "name": "photo_id",
      "labelZh": "Flickr 照片 ID",
      "type": "string",
      "required": true,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "Flickr 照片 ID，用來避免重複匯入。"
    },
    {
      "name": "photo_url",
      "labelZh": "Flickr 公開頁面",
      "type": "url",
      "required": true,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "Flickr 公開頁面，用來回到原始照片確認脈絡。"
    },
    {
      "name": "album_ids",
      "labelZh": "來源相簿 ID",
      "type": "string",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "",
      "descriptionZh": "這張照片曾由哪些 Flickr 相簿匯入或關聯。多值以分號分隔。"
    },
    {
      "name": "image_preview_url",
      "labelZh": "縮圖 URL",
      "type": "url",
      "required": true,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "搜尋介面顯示用縮圖。"
    },
    {
      "name": "album_title",
      "labelZh": "相簿名稱",
      "type": "string",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "Flickr 相簿名稱。若工具暫時抓不到，可以留空。"
    },
    {
      "name": "event_name",
      "labelZh": "活動名稱",
      "type": "string",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "例如 SITCON 年會、SITCON Camp。不確定就留空。"
    },
    {
      "name": "event_year",
      "labelZh": "活動年份",
      "type": "year",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "四位年份，例如 2026。"
    },
    {
      "name": "people_count",
      "labelZh": "照片中的人數",
      "type": "integer",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "照片中可辨識的人數估計值。可留空；若無人可填 0，值必須是非負整數。"
    },
    {
      "name": "subject_type",
      "labelZh": "主要視覺主體",
      "type": "taxonomy",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "subject_type",
      "descriptionZh": "照片海初篩用的主要視覺主體粗分類，例如人物、物件、餐食茶點、文字標示、螢幕或空間。只描述主體種類，不描述活動場景、人數規模或用途。"
    },
    {
      "name": "photographer",
      "labelZh": "攝影師署名",
      "type": "string",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "攝影師署名。SITCON 是 Flickr 帳號擁有者，不等於攝影師。"
    },
    {
      "name": "license",
      "labelZh": "授權資訊",
      "type": "string",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "Flickr 顯示的授權資訊。不確定時留空並使用 needs_review。"
    },
    {
      "name": "scene_tags",
      "labelZh": "場景標籤",
      "type": "taxonomy",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "scene_tags",
      "descriptionZh": "照片中看見的事實，例如攤位、會眾、舞台。"
    },
    {
      "name": "mood_tags",
      "labelZh": "氛圍標籤",
      "type": "taxonomy",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "mood_tags",
      "descriptionZh": "照片帶來的感受，例如熱鬧、專注、青春感。"
    },
    {
      "name": "recommended_uses",
      "labelZh": "建議用途",
      "type": "taxonomy",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "recommended_uses",
      "descriptionZh": "適合的工作用途，例如社群貼文、贊助提案。"
    },
    {
      "name": "sponsorship_items",
      "labelZh": "贊助品項",
      "type": "taxonomy",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "sponsorship_items",
      "descriptionZh": "對應 CFS 贊助品項，必須對齊 data/sponsorship-items.json。"
    },
    {
      "name": "sponsorship_tags",
      "labelZh": "贊助價值",
      "type": "taxonomy",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "sponsorship_tags",
      "descriptionZh": "贊助價值或佐證用途，例如品牌露出、會眾互動。"
    },
    {
      "name": "orientation",
      "labelZh": "照片方向",
      "type": "taxonomy",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "orientation",
      "descriptionZh": "landscape、portrait、square。"
    },
    {
      "name": "has_negative_space",
      "labelZh": "是否有留白",
      "type": "boolean",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "true 或 false，表示是否有明顯留白可放字。"
    },
    {
      "name": "safe_crop",
      "labelZh": "安全裁切比例",
      "type": "taxonomy",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "safe_crop",
      "descriptionZh": "適合裁切的比例，例如 1:1、16:9。"
    },
    {
      "name": "visual_description",
      "labelZh": "畫面描述",
      "type": "text",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "1 到 2 句中立的可見畫面描述，用於自然語言找圖輔助。只描述照片中看得到的物件、動作、文字、位置與空間關係，不自行補活動名稱、年份、身份、單位或贊助推論。"
    },
    {
      "name": "public_use_status",
      "labelZh": "公開使用狀態",
      "type": "taxonomy",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "public_use_status",
      "descriptionZh": "approved、needs_review、avoid。不確定用 needs_review。"
    },
    {
      "name": "priority_level",
      "labelZh": "推薦優先度",
      "type": "taxonomy",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "priority_level",
      "descriptionZh": "high、normal、low。表示推薦使用優先度，不是照片品質分數。"
    },
    {
      "name": "collections",
      "labelZh": "素材包",
      "type": "string",
      "required": false,
      "multiValue": true,
      "taxonomyKey": "",
      "descriptionZh": "素材包，例如志工招募、贊助提案、網站橫幅。"
    },
    {
      "name": "curation_notes",
      "labelZh": "整理備註",
      "type": "text",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "",
      "descriptionZh": "公開 repo 與正式 Sheets 中仍視為公開資料，不要寫入敏感內部資訊。"
    },
    {
      "name": "curation_status",
      "labelZh": "整理狀態",
      "type": "taxonomy",
      "required": false,
      "multiValue": false,
      "taxonomyKey": "curation_status",
      "descriptionZh": "unreviewed、ai_labeled、reviewed。精選或封存不放在整理狀態；優先推薦用 priority_level 或 collections，避免推薦用 public_use_status = avoid。"
    }
  ],
  "reviewedRequiredFields": [
    "subject_type",
    "scene_tags"
  ],
  "taxonomy": {
    "scene_tags": [
      "講者",
      "會眾",
      "報到",
      "攤位",
      "工作人員",
      "合照",
      "交流",
      "舞台",
      "背板",
      "茶點",
      "手作",
      "工作坊",
      "排隊",
      "休息區",
      "直播",
      "攝影",
      "指標",
      "場地",
      "場佈",
      "螢幕",
      "頒獎",
      "兒童",
      "錄音",
      "導覽"
    ],
    "subject_type": [
      "people",
      "object",
      "food",
      "text_signage",
      "screen",
      "space"
    ],
    "mood_tags": [
      "熱鬧",
      "專注",
      "溫暖",
      "青春感",
      "專業",
      "幕後感",
      "友善",
      "交流感",
      "成就感",
      "儀式感",
      "活力",
      "安靜"
    ],
    "recommended_uses": [
      "社群貼文",
      "網站橫幅",
      "志工招募",
      "投稿宣傳",
      "報名宣傳",
      "贊助提案",
      "贊助成果報告",
      "新聞稿",
      "活動回顧",
      "社群介紹",
      "講者宣傳",
      "簡報"
    ],
    "sponsorship_items": [
      "Badge 繩廠商 Logo 曝光",
      "年會 T-shirt Logo 曝光",
      "獨家帆布袋",
      "獨家導遊團行程",
      "會議室椅套曝光",
      "午餐旗、點心旗",
      "獨家議程",
      "遠距會議室議程",
      "SITCON 貼紙置入",
      "年會開閉幕口播",
      "一次性紙餐墊",
      "拍貼機贊助商方案",
      "SITCON 會場指標置入",
      "會場攤位加大",
      "樓梯打卡牆",
      "洗手間標語曝光",
      "接駁車車內廣播",
      "入口落地窗背板 Logo 曝光",
      "會場電視輪播",
      "會場攤位",
      "SITCON 網站議程表置入",
      "SITCON 與會者 Email 推播置入",
      "工作人員徽章曝光",
      "明信片",
      "面紙包",
      "年會意象背板",
      "網路宣傳",
      "「遠道而來票」獨家冠名",
      "OPass App 推播公告",
      "樓梯欄杆垂掛布條展出",
      "R0 影片輪播",
      "R0 影片輪播加時",
      "議程廳講者背板",
      "R0 議程前夥伴宣讀",
      "錄影模板  Logo 曝光",
      "迎賓袋文宣",
      "網頁 Logo 曝光",
      "年會共筆 Logo 曝光",
      "門口議程表 Logo 曝光",
      "贈票"
    ],
    "sponsorship_tags": [
      "攤位曝光",
      "品牌露出",
      "會眾互動",
      "實體導流",
      "主舞台曝光",
      "議程曝光",
      "線上曝光",
      "參與者體驗",
      "贊助成果佐證",
      "觸及學生族群",
      "社群信任感",
      "合作夥伴形象"
    ],
    "orientation": [
      "landscape",
      "portrait",
      "square"
    ],
    "safe_crop": [
      "1:1",
      "16:9",
      "9:16"
    ],
    "public_use_status": [
      "approved",
      "needs_review",
      "avoid"
    ],
    "priority_level": [
      "high",
      "normal",
      "low"
    ],
    "curation_status": [
      "unreviewed",
      "ai_labeled",
      "reviewed"
    ],
    "option_labels": {
      "subject_type": {
        "people": "人物",
        "object": "物件",
        "food": "餐食茶點",
        "text_signage": "文字標示",
        "screen": "螢幕",
        "space": "空間"
      },
      "orientation": {
        "landscape": "橫式",
        "portrait": "直式",
        "square": "方形"
      },
      "public_use_status": {
        "approved": "已確認",
        "needs_review": "待整理確認",
        "avoid": "不建議"
      },
      "priority_level": {
        "high": "優先推薦",
        "normal": "一般候選",
        "low": "低優先"
      },
      "curation_status": {
        "unreviewed": "未整理",
        "ai_labeled": "AI 初標",
        "reviewed": "已整理"
      },
      "recommended_uses": {
        "社群貼文": "社群貼文",
        "網站橫幅": "網站橫幅",
        "志工招募": "志工招募",
        "投稿宣傳": "投稿宣傳",
        "報名宣傳": "報名宣傳",
        "贊助提案": "贊助提案",
        "贊助成果報告": "贊助成果",
        "新聞稿": "新聞稿",
        "活動回顧": "活動回顧",
        "社群介紹": "社群介紹",
        "講者宣傳": "講者宣傳",
        "簡報": "簡報"
      },
      "has_negative_space": {
        "true": "有留白",
        "false": "無明顯留白"
      }
    },
    "sponsorship_item_categories": [
      "打包專屬",
      "數位媒體曝光",
      "更多曝光方式",
      "獨家議程",
      "現場實體曝光",
      "紀念品配件曝光"
    ]
  },
  "publicSensitiveContentRules": {
    "public_text_fields": [
      "album_title",
      "event_name",
      "photographer",
      "license",
      "visual_description",
      "collections",
      "curation_notes"
    ],
    "rules": [
      {
        "id": "email",
        "label_zh": "email 位址",
        "pattern": "[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}",
        "flags": "i"
      },
      {
        "id": "phone",
        "label_zh": "疑似電話號碼",
        "pattern": "(?:^|[^0-9])(?:(?:電話|手機|聯絡|tel|phone|mobile)[:：\\s]*)?(?:\\+?886[-\\s]?)?(?:0?9\\d{2}[-\\s]?\\d{3}[-\\s]?\\d{3}|0[2-8][-\\s]?\\d{3,4}[-\\s]?\\d{4}|\\(0[2-8]\\)\\s?\\d{3,4}[-\\s]?\\d{4})(?=$|[^0-9])",
        "flags": ""
      },
      {
        "id": "private_google_link",
        "label_zh": "疑似私人 Google Drive/Docs 連結",
        "pattern": "https?://(?:docs|drive)\\.google\\.com/\\S+",
        "flags": "i"
      },
      {
        "id": "private_chat_link",
        "label_zh": "疑似 Slack/Discord 私人頻道連結",
        "pattern": "https?://\\S*(?:slack\\.com/archives|discord(?:app)?\\.com/channels|discord\\.gg)/\\S+",
        "flags": "i"
      },
      {
        "id": "internal_terms",
        "label_zh": "內部或不公開字眼",
        "pattern": "(?:內部|不公開|不要公開|暫勿公開|不外流|機密|confidential|internal only|private)",
        "flags": "i"
      },
      {
        "id": "token_keyword",
        "label_zh": "敏感憑證相關字眼",
        "pattern": "(?:api[_ -]?key|access[_ -]?token|refresh[_ -]?token|secret)",
        "flags": "i"
      },
      {
        "id": "token_value",
        "label_zh": "疑似 token、secret 或 API key 值",
        "pattern": "(?:bearer\\s+[A-Za-z0-9._~+/=-]{16,}|sk-[A-Za-z0-9_-]{20,}|ghp_[A-Za-z0-9_]{20,}|github_pat_[A-Za-z0-9_]{20,})",
        "flags": "i"
      }
    ]
  },
  "taxonomySheet": {
    "headers": [
      "taxonomy_key",
      "value",
      "label_zh",
      "order"
    ],
    "rows": [
      {
        "taxonomy_key": "scene_tags",
        "value": "講者",
        "label_zh": "講者",
        "order": "1"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "會眾",
        "label_zh": "會眾",
        "order": "2"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "報到",
        "label_zh": "報到",
        "order": "3"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "攤位",
        "label_zh": "攤位",
        "order": "4"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "工作人員",
        "label_zh": "工作人員",
        "order": "5"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "合照",
        "label_zh": "合照",
        "order": "6"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "交流",
        "label_zh": "交流",
        "order": "7"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "舞台",
        "label_zh": "舞台",
        "order": "8"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "背板",
        "label_zh": "背板",
        "order": "9"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "茶點",
        "label_zh": "茶點",
        "order": "10"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "手作",
        "label_zh": "手作",
        "order": "11"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "工作坊",
        "label_zh": "工作坊",
        "order": "12"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "排隊",
        "label_zh": "排隊",
        "order": "13"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "休息區",
        "label_zh": "休息區",
        "order": "14"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "直播",
        "label_zh": "直播",
        "order": "15"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "攝影",
        "label_zh": "攝影",
        "order": "16"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "指標",
        "label_zh": "指標",
        "order": "17"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "場地",
        "label_zh": "場地",
        "order": "18"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "場佈",
        "label_zh": "場佈",
        "order": "19"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "螢幕",
        "label_zh": "螢幕",
        "order": "20"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "頒獎",
        "label_zh": "頒獎",
        "order": "21"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "兒童",
        "label_zh": "兒童",
        "order": "22"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "錄音",
        "label_zh": "錄音",
        "order": "23"
      },
      {
        "taxonomy_key": "scene_tags",
        "value": "導覽",
        "label_zh": "導覽",
        "order": "24"
      },
      {
        "taxonomy_key": "subject_type",
        "value": "people",
        "label_zh": "人物",
        "order": "1"
      },
      {
        "taxonomy_key": "subject_type",
        "value": "object",
        "label_zh": "物件",
        "order": "2"
      },
      {
        "taxonomy_key": "subject_type",
        "value": "food",
        "label_zh": "餐食茶點",
        "order": "3"
      },
      {
        "taxonomy_key": "subject_type",
        "value": "text_signage",
        "label_zh": "文字標示",
        "order": "4"
      },
      {
        "taxonomy_key": "subject_type",
        "value": "screen",
        "label_zh": "螢幕",
        "order": "5"
      },
      {
        "taxonomy_key": "subject_type",
        "value": "space",
        "label_zh": "空間",
        "order": "6"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "熱鬧",
        "label_zh": "熱鬧",
        "order": "1"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "專注",
        "label_zh": "專注",
        "order": "2"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "溫暖",
        "label_zh": "溫暖",
        "order": "3"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "青春感",
        "label_zh": "青春感",
        "order": "4"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "專業",
        "label_zh": "專業",
        "order": "5"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "幕後感",
        "label_zh": "幕後感",
        "order": "6"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "友善",
        "label_zh": "友善",
        "order": "7"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "交流感",
        "label_zh": "交流感",
        "order": "8"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "成就感",
        "label_zh": "成就感",
        "order": "9"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "儀式感",
        "label_zh": "儀式感",
        "order": "10"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "活力",
        "label_zh": "活力",
        "order": "11"
      },
      {
        "taxonomy_key": "mood_tags",
        "value": "安靜",
        "label_zh": "安靜",
        "order": "12"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "社群貼文",
        "label_zh": "社群貼文",
        "order": "1"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "網站橫幅",
        "label_zh": "網站橫幅",
        "order": "2"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "志工招募",
        "label_zh": "志工招募",
        "order": "3"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "投稿宣傳",
        "label_zh": "投稿宣傳",
        "order": "4"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "報名宣傳",
        "label_zh": "報名宣傳",
        "order": "5"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "贊助提案",
        "label_zh": "贊助提案",
        "order": "6"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "贊助成果報告",
        "label_zh": "贊助成果",
        "order": "7"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "新聞稿",
        "label_zh": "新聞稿",
        "order": "8"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "活動回顧",
        "label_zh": "活動回顧",
        "order": "9"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "社群介紹",
        "label_zh": "社群介紹",
        "order": "10"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "講者宣傳",
        "label_zh": "講者宣傳",
        "order": "11"
      },
      {
        "taxonomy_key": "recommended_uses",
        "value": "簡報",
        "label_zh": "簡報",
        "order": "12"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "Badge 繩廠商 Logo 曝光",
        "label_zh": "Badge 繩廠商 Logo 曝光",
        "order": "1"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "年會 T-shirt Logo 曝光",
        "label_zh": "年會 T-shirt Logo 曝光",
        "order": "2"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "獨家帆布袋",
        "label_zh": "獨家帆布袋",
        "order": "3"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "獨家導遊團行程",
        "label_zh": "獨家導遊團行程",
        "order": "4"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "會議室椅套曝光",
        "label_zh": "會議室椅套曝光",
        "order": "5"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "午餐旗、點心旗",
        "label_zh": "午餐旗、點心旗",
        "order": "6"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "獨家議程",
        "label_zh": "獨家議程",
        "order": "7"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "遠距會議室議程",
        "label_zh": "遠距會議室議程",
        "order": "8"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "SITCON 貼紙置入",
        "label_zh": "SITCON 貼紙置入",
        "order": "9"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "年會開閉幕口播",
        "label_zh": "年會開閉幕口播",
        "order": "10"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "一次性紙餐墊",
        "label_zh": "一次性紙餐墊",
        "order": "11"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "拍貼機贊助商方案",
        "label_zh": "拍貼機贊助商方案",
        "order": "12"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "SITCON 會場指標置入",
        "label_zh": "SITCON 會場指標置入",
        "order": "13"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "會場攤位加大",
        "label_zh": "會場攤位加大",
        "order": "14"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "樓梯打卡牆",
        "label_zh": "樓梯打卡牆",
        "order": "15"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "洗手間標語曝光",
        "label_zh": "洗手間標語曝光",
        "order": "16"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "接駁車車內廣播",
        "label_zh": "接駁車車內廣播",
        "order": "17"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "入口落地窗背板 Logo 曝光",
        "label_zh": "入口落地窗背板 Logo 曝光",
        "order": "18"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "會場電視輪播",
        "label_zh": "會場電視輪播",
        "order": "19"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "會場攤位",
        "label_zh": "會場攤位",
        "order": "20"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "SITCON 網站議程表置入",
        "label_zh": "SITCON 網站議程表置入",
        "order": "21"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "SITCON 與會者 Email 推播置入",
        "label_zh": "SITCON 與會者 Email 推播置入",
        "order": "22"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "工作人員徽章曝光",
        "label_zh": "工作人員徽章曝光",
        "order": "23"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "明信片",
        "label_zh": "明信片",
        "order": "24"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "面紙包",
        "label_zh": "面紙包",
        "order": "25"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "年會意象背板",
        "label_zh": "年會意象背板",
        "order": "26"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "網路宣傳",
        "label_zh": "網路宣傳",
        "order": "27"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "「遠道而來票」獨家冠名",
        "label_zh": "「遠道而來票」獨家冠名",
        "order": "28"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "OPass App 推播公告",
        "label_zh": "OPass App 推播公告",
        "order": "29"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "樓梯欄杆垂掛布條展出",
        "label_zh": "樓梯欄杆垂掛布條展出",
        "order": "30"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "R0 影片輪播",
        "label_zh": "R0 影片輪播",
        "order": "31"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "R0 影片輪播加時",
        "label_zh": "R0 影片輪播加時",
        "order": "32"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "議程廳講者背板",
        "label_zh": "議程廳講者背板",
        "order": "33"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "R0 議程前夥伴宣讀",
        "label_zh": "R0 議程前夥伴宣讀",
        "order": "34"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "錄影模板  Logo 曝光",
        "label_zh": "錄影模板  Logo 曝光",
        "order": "35"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "迎賓袋文宣",
        "label_zh": "迎賓袋文宣",
        "order": "36"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "網頁 Logo 曝光",
        "label_zh": "網頁 Logo 曝光",
        "order": "37"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "年會共筆 Logo 曝光",
        "label_zh": "年會共筆 Logo 曝光",
        "order": "38"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "門口議程表 Logo 曝光",
        "label_zh": "門口議程表 Logo 曝光",
        "order": "39"
      },
      {
        "taxonomy_key": "sponsorship_items",
        "value": "贈票",
        "label_zh": "贈票",
        "order": "40"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "攤位曝光",
        "label_zh": "攤位曝光",
        "order": "1"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "品牌露出",
        "label_zh": "品牌露出",
        "order": "2"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "會眾互動",
        "label_zh": "會眾互動",
        "order": "3"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "實體導流",
        "label_zh": "實體導流",
        "order": "4"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "主舞台曝光",
        "label_zh": "主舞台曝光",
        "order": "5"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "議程曝光",
        "label_zh": "議程曝光",
        "order": "6"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "線上曝光",
        "label_zh": "線上曝光",
        "order": "7"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "參與者體驗",
        "label_zh": "參與者體驗",
        "order": "8"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "贊助成果佐證",
        "label_zh": "贊助成果佐證",
        "order": "9"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "觸及學生族群",
        "label_zh": "觸及學生族群",
        "order": "10"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "社群信任感",
        "label_zh": "社群信任感",
        "order": "11"
      },
      {
        "taxonomy_key": "sponsorship_tags",
        "value": "合作夥伴形象",
        "label_zh": "合作夥伴形象",
        "order": "12"
      },
      {
        "taxonomy_key": "orientation",
        "value": "landscape",
        "label_zh": "橫式",
        "order": "1"
      },
      {
        "taxonomy_key": "orientation",
        "value": "portrait",
        "label_zh": "直式",
        "order": "2"
      },
      {
        "taxonomy_key": "orientation",
        "value": "square",
        "label_zh": "方形",
        "order": "3"
      },
      {
        "taxonomy_key": "safe_crop",
        "value": "1:1",
        "label_zh": "1:1",
        "order": "1"
      },
      {
        "taxonomy_key": "safe_crop",
        "value": "16:9",
        "label_zh": "16:9",
        "order": "2"
      },
      {
        "taxonomy_key": "safe_crop",
        "value": "9:16",
        "label_zh": "9:16",
        "order": "3"
      },
      {
        "taxonomy_key": "public_use_status",
        "value": "approved",
        "label_zh": "已確認",
        "order": "1"
      },
      {
        "taxonomy_key": "public_use_status",
        "value": "needs_review",
        "label_zh": "待整理確認",
        "order": "2"
      },
      {
        "taxonomy_key": "public_use_status",
        "value": "avoid",
        "label_zh": "不建議",
        "order": "3"
      },
      {
        "taxonomy_key": "priority_level",
        "value": "high",
        "label_zh": "優先推薦",
        "order": "1"
      },
      {
        "taxonomy_key": "priority_level",
        "value": "normal",
        "label_zh": "一般候選",
        "order": "2"
      },
      {
        "taxonomy_key": "priority_level",
        "value": "low",
        "label_zh": "低優先",
        "order": "3"
      },
      {
        "taxonomy_key": "curation_status",
        "value": "unreviewed",
        "label_zh": "未整理",
        "order": "1"
      },
      {
        "taxonomy_key": "curation_status",
        "value": "ai_labeled",
        "label_zh": "AI 初標",
        "order": "2"
      },
      {
        "taxonomy_key": "curation_status",
        "value": "reviewed",
        "label_zh": "已整理",
        "order": "3"
      },
      {
        "taxonomy_key": "sponsorship_item_categories",
        "value": "打包專屬",
        "label_zh": "打包專屬",
        "order": "1"
      },
      {
        "taxonomy_key": "sponsorship_item_categories",
        "value": "數位媒體曝光",
        "label_zh": "數位媒體曝光",
        "order": "2"
      },
      {
        "taxonomy_key": "sponsorship_item_categories",
        "value": "更多曝光方式",
        "label_zh": "更多曝光方式",
        "order": "3"
      },
      {
        "taxonomy_key": "sponsorship_item_categories",
        "value": "獨家議程",
        "label_zh": "獨家議程",
        "order": "4"
      },
      {
        "taxonomy_key": "sponsorship_item_categories",
        "value": "現場實體曝光",
        "label_zh": "現場實體曝光",
        "order": "5"
      },
      {
        "taxonomy_key": "sponsorship_item_categories",
        "value": "紀念品配件曝光",
        "label_zh": "紀念品配件曝光",
        "order": "6"
      }
    ]
  },
  "validationMessages": {
    "completionRequired": "完成審核需要填寫此欄位",
    "completionWarning": "完成審核前需填寫",
    "duplicateListPrefix": "不可重複填寫：",
    "invalidBoolean": "必須是 true 或 false",
    "invalidInteger": "必須是非負整數",
    "invalidUrl": "必須是 http 或 https URL",
    "invalidYear": "必須是四位數年份",
    "required": "必填欄位不可空白",
    "unknownTaxonomyPrefix": "未知受控字彙："
  },
  "interfaceRegistry": {
    "version": "2026-1.0.0",
    "pages": {
      "settings": {
        "pageSize": 96,
        "searchDebounceMs": 180,
        "resultTrackingDelayMs": 600,
        "discoverWindowSize": 24,
        "discoverHistorySize": 12
      },
      "filters": [
        {
          "key": "album",
          "label": "活動/相簿",
          "group": "core",
          "control": "album",
          "urlKey": "album",
          "source": {
            "type": "album"
          },
          "emptyLabel": "全部活動/相簿",
          "searchPlaceholder": "搜尋活動或相簿"
        },
        {
          "key": "use",
          "field": "recommended_uses",
          "filterParam": "recommendedUse",
          "label": "用途",
          "group": "general",
          "control": "use",
          "urlKey": "use",
          "source": {
            "type": "taxonomy",
            "key": "recommended_uses"
          },
          "emptyLabel": "全部用途",
          "searchPlaceholder": "搜尋用途"
        },
        {
          "key": "mood",
          "field": "mood_tags",
          "filterParam": "mood",
          "label": "氛圍",
          "group": "general",
          "control": "mood",
          "urlKey": "mood",
          "source": {
            "type": "taxonomy",
            "key": "mood_tags"
          },
          "emptyLabel": "全部氛圍",
          "searchPlaceholder": "搜尋氛圍"
        },
        {
          "key": "scene",
          "field": "scene_tags",
          "filterParam": "scene",
          "label": "場景",
          "group": "general",
          "control": "scene",
          "urlKey": "scene",
          "source": {
            "type": "taxonomy",
            "key": "scene_tags"
          },
          "emptyLabel": "全部場景",
          "searchPlaceholder": "搜尋場景"
        },
        {
          "key": "peopleCount",
          "field": "people_count",
          "filterParam": "peopleCount",
          "label": "人數",
          "group": "details",
          "control": "peopleCount",
          "urlKey": "people",
          "source": {
            "type": "people_count_buckets"
          },
          "emptyLabel": "全部人數",
          "searchPlaceholder": "搜尋人數"
        },
        {
          "key": "subjectType",
          "field": "subject_type",
          "filterParam": "subjectType",
          "label": "主體",
          "group": "details",
          "control": "subjectType",
          "urlKey": "subject",
          "source": {
            "type": "taxonomy",
            "key": "subject_type",
            "labels": true
          },
          "emptyLabel": "全部主體",
          "searchPlaceholder": "搜尋主體"
        },
        {
          "key": "orientation",
          "field": "orientation",
          "filterParam": "orientation",
          "label": "方向",
          "group": "visual",
          "control": "orientation",
          "urlKey": "orientation",
          "source": {
            "type": "taxonomy",
            "key": "orientation",
            "labels": true
          },
          "emptyLabel": "全部方向",
          "searchPlaceholder": "搜尋方向"
        },
        {
          "key": "negativeSpace",
          "field": "has_negative_space",
          "filterParam": "negativeSpace",
          "label": "留白",
          "group": "visual",
          "control": "negativeSpace",
          "urlKey": "negative",
          "source": {
            "type": "boolean",
            "labels": true
          },
          "emptyLabel": "全部留白狀態",
          "searchPlaceholder": "搜尋留白狀態"
        },
        {
          "key": "safeCrop",
          "field": "safe_crop",
          "filterParam": "safeCrop",
          "label": "裁切",
          "group": "visual",
          "control": "safeCrop",
          "urlKey": "crop",
          "source": {
            "type": "taxonomy",
            "key": "safe_crop"
          },
          "emptyLabel": "全部裁切",
          "searchPlaceholder": "搜尋裁切"
        },
        {
          "key": "sponsorshipTag",
          "field": "sponsorship_tags",
          "filterParam": "sponsorshipTag",
          "label": "贊助價值",
          "group": "sponsor",
          "control": "sponsorshipTag",
          "urlKey": "sponsorTag",
          "source": {
            "type": "taxonomy",
            "key": "sponsorship_tags"
          },
          "emptyLabel": "全部贊助價值",
          "searchPlaceholder": "搜尋贊助價值"
        },
        {
          "key": "sponsorshipItem",
          "field": "sponsorship_items",
          "filterParam": "sponsorshipItem",
          "label": "贊助品項",
          "group": "sponsor",
          "control": "sponsorshipItem",
          "urlKey": "sponsorItem",
          "source": {
            "type": "taxonomy_autocomplete",
            "key": "sponsorship_items"
          },
          "searchPlaceholder": "搜尋品項"
        },
        {
          "key": "publicStatus",
          "field": "public_use_status",
          "filterParam": "publicStatus",
          "label": "使用提醒",
          "group": "status",
          "control": "publicStatus",
          "urlKey": "public",
          "source": {
            "type": "taxonomy",
            "key": "public_use_status",
            "labels": true
          },
          "emptyLabel": "全部使用提醒",
          "searchPlaceholder": "搜尋使用提醒",
          "lowLevel": true
        },
        {
          "key": "priority",
          "field": "priority_level",
          "filterParam": "priority",
          "label": "優先度",
          "group": "status",
          "control": "priority",
          "urlKey": "priority",
          "source": {
            "type": "taxonomy",
            "key": "priority_level",
            "labels": true
          },
          "emptyLabel": "全部優先度",
          "searchPlaceholder": "搜尋優先度",
          "lowLevel": true
        },
        {
          "key": "curationStatus",
          "field": "curation_status",
          "filterParam": "curationStatus",
          "label": "整理狀態",
          "group": "status",
          "control": "curationStatus",
          "urlKey": "curation",
          "source": {
            "type": "taxonomy",
            "key": "curation_status",
            "labels": true
          },
          "emptyLabel": "全部整理狀態",
          "searchPlaceholder": "搜尋整理狀態",
          "lowLevel": true
        },
        {
          "key": "collection",
          "field": "collections",
          "filterParam": "collection",
          "label": "素材包",
          "group": "details",
          "control": "collection",
          "urlKey": "collection",
          "source": {
            "type": "photo_values"
          },
          "emptyLabel": "全部素材包",
          "searchPlaceholder": "搜尋素材包"
        }
      ],
      "defaultPrimaryFilters": [
        "use",
        "scene",
        "orientation",
        "safeCrop",
        "negativeSpace",
        "mood"
      ],
      "peopleCountBuckets": [
        {
          "label": "全部人數",
          "value": ""
        },
        {
          "label": "未標記",
          "value": "unknown",
          "missing": true
        },
        {
          "label": "無人",
          "value": "0",
          "min": 0,
          "max": 0
        },
        {
          "label": "1 人",
          "value": "1",
          "min": 1,
          "max": 1
        },
        {
          "label": "2-5 人",
          "value": "2-5",
          "min": 2,
          "max": 5
        },
        {
          "label": "6-20 人",
          "value": "6-20",
          "min": 6,
          "max": 20
        },
        {
          "label": "21 人以上",
          "value": "21+",
          "min": 21
        }
      ],
      "taskModes": [
        {
          "id": "all",
          "label": "全部照片",
          "description": "不套任務權重"
        },
        {
          "id": "social",
          "label": "社群貼文",
          "description": "友善、交流、可裁切",
          "primaryFilters": [
            "use",
            "scene",
            "orientation",
            "safeCrop",
            "negativeSpace",
            "mood"
          ],
          "recommendedUses": [
            "社群貼文",
            "社群介紹",
            "活動回顧"
          ],
          "moods": [
            "友善",
            "交流感",
            "青春感",
            "活力",
            "熱鬧"
          ],
          "scenes": [
            "會眾",
            "交流",
            "工作人員"
          ],
          "safeCrops": [
            "1:1",
            "16:9",
            "9:16"
          ],
          "prefersNegativeSpace": true
        },
        {
          "id": "hero",
          "label": "網站橫幅",
          "description": "橫式、留白、可放標題",
          "primaryFilters": [
            "orientation",
            "negativeSpace",
            "safeCrop",
            "scene",
            "mood"
          ],
          "recommendedUses": [
            "網站橫幅",
            "社群介紹"
          ],
          "moods": [
            "專業",
            "青春感",
            "友善"
          ],
          "scenes": [
            "舞台",
            "會眾",
            "交流",
            "場地",
            "背板"
          ],
          "orientations": [
            "landscape"
          ],
          "safeCrops": [
            "16:9"
          ],
          "prefersNegativeSpace": true
        },
        {
          "id": "visual",
          "label": "設計素材",
          "description": "版面背景、簡報與延伸素材",
          "primaryFilters": [
            "orientation",
            "negativeSpace",
            "safeCrop",
            "scene",
            "mood"
          ],
          "recommendedUses": [
            "網站橫幅",
            "社群貼文",
            "簡報"
          ],
          "moods": [
            "專業",
            "青春感",
            "活力",
            "安靜"
          ],
          "scenes": [
            "場地",
            "背板",
            "舞台",
            "交流"
          ],
          "orientations": [
            "landscape",
            "square"
          ],
          "safeCrops": [
            "16:9",
            "1:1",
            "9:16"
          ],
          "prefersNegativeSpace": true
        },
        {
          "id": "sponsor-pitch",
          "label": "贊助提案",
          "description": "互動、觸及、品牌價值",
          "primaryFilters": [
            "sponsorshipTag",
            "sponsorshipItem",
            "scene",
            "orientation",
            "negativeSpace"
          ],
          "recommendedUses": [
            "贊助提案",
            "簡報"
          ],
          "moods": [
            "熱鬧",
            "專業",
            "交流感"
          ],
          "scenes": [
            "攤位",
            "會眾",
            "交流",
            "舞台"
          ],
          "sponsorshipTags": [
            "品牌露出",
            "會眾互動",
            "觸及學生族群",
            "社群信任感",
            "參與者體驗"
          ]
        },
        {
          "id": "sponsor-report",
          "label": "贊助成果",
          "description": "品項與成果佐證",
          "primaryFilters": [
            "sponsorshipItem",
            "sponsorshipTag",
            "scene"
          ],
          "recommendedUses": [
            "贊助成果報告"
          ],
          "scenes": [
            "攤位",
            "會眾",
            "背板",
            "舞台",
            "螢幕"
          ],
          "sponsorshipTags": [
            "贊助成果佐證",
            "品牌露出",
            "會眾互動",
            "主舞台曝光",
            "議程曝光"
          ]
        },
        {
          "id": "press",
          "label": "新聞稿/簡報",
          "description": "正式、代表性、可追溯",
          "primaryFilters": [
            "scene",
            "orientation",
            "use",
            "mood"
          ],
          "recommendedUses": [
            "新聞稿",
            "簡報",
            "社群介紹",
            "活動回顧"
          ],
          "moods": [
            "專業",
            "專注",
            "儀式感",
            "交流感"
          ],
          "scenes": [
            "舞台",
            "講者",
            "會眾",
            "背板",
            "場地"
          ],
          "orientations": [
            "landscape"
          ]
        },
        {
          "id": "volunteer",
          "label": "志工招募",
          "description": "幕後、活力、參與感",
          "primaryFilters": [
            "use",
            "scene",
            "mood",
            "orientation"
          ],
          "recommendedUses": [
            "志工招募"
          ],
          "moods": [
            "幕後感",
            "友善",
            "青春感",
            "活力"
          ],
          "scenes": [
            "工作人員",
            "交流",
            "報到",
            "攝影"
          ]
        },
        {
          "id": "recap",
          "label": "活動回顧",
          "description": "規模、交流、成果",
          "primaryFilters": [
            "use",
            "scene",
            "mood",
            "orientation"
          ],
          "recommendedUses": [
            "活動回顧",
            "社群介紹"
          ],
          "moods": [
            "熱鬧",
            "成就感",
            "交流感",
            "儀式感"
          ],
          "scenes": [
            "會眾",
            "舞台",
            "合照",
            "交流",
            "講者"
          ]
        }
      ],
      "statusPolicy": {
        "public_use_status": {
          "approved": 0,
          "needs_review": -10,
          "avoid": -160
        },
        "curation_status": {
          "reviewed": 60,
          "ai_labeled": 25,
          "unreviewed": 0
        },
        "priority_level": {
          "high": 80,
          "normal": 25,
          "low": -10
        }
      },
      "taskScoreWeights": {
        "recommendedUses": 150,
        "moods": 45,
        "scenes": 45,
        "sponsorshipTags": 65,
        "orientations": 35,
        "safeCrops": 35,
        "prefersNegativeSpace": 35,
        "hasPreviewImage": 10,
        "missingPreviewImage": -50
      },
      "queryPhraseAliases": {
        "可放字": [
          "可放字",
          "留白",
          "negative space"
        ],
        "放字": [
          "可放字",
          "留白",
          "negative space"
        ],
        "留白": [
          "留白",
          "可放字",
          "negative space"
        ],
        "網站橫幅": [
          "網站橫幅",
          "網頁橫幅",
          "橫幅",
          "背景素材"
        ],
        "版面背景": [
          "版面背景",
          "背景素材",
          "橫幅",
          "網站橫幅"
        ],
        "logo": [
          "logo",
          "品牌露出",
          "背板"
        ],
        "品牌": [
          "品牌",
          "品牌露出",
          "贊助成果佐證"
        ],
        "社群感": [
          "社群感",
          "社群介紹",
          "交流感",
          "友善"
        ],
        "友善交流": [
          "友善",
          "交流感",
          "交流"
        ],
        "舞台講者": [
          "舞台",
          "講者",
          "新聞稿",
          "簡報"
        ],
        "志工": [
          "志工",
          "志工招募",
          "工作人員",
          "幕後感"
        ],
        "正式": [
          "正式",
          "專業",
          "新聞稿",
          "簡報"
        ]
      }
    },
    "appsScript": {
      "publicReadFields": [
        "curation_status",
        "public_use_status",
        "priority_level",
        "collections"
      ],
      "reviewPanel": {
        "bufferBefore": 10,
        "bufferAfter": 10,
        "fields": [
          "people_count",
          "subject_type",
          "scene_tags",
          "mood_tags",
          "recommended_uses",
          "sponsorship_items",
          "sponsorship_tags",
          "orientation",
          "has_negative_space",
          "safe_crop",
          "visual_description",
          "public_use_status",
          "priority_level",
          "collections",
          "curation_notes"
        ]
      },
      "reviewWebApp": {
        "listFields": [
          "photo_id",
          "photo_url",
          "image_preview_url",
          "album_title",
          "event_name",
          "event_year",
          "scene_tags",
          "recommended_uses",
          "sponsorship_items",
          "public_use_status",
          "priority_level",
          "curation_status",
          "visual_description",
          "curation_notes"
        ],
        "filterFields": [
          "curation_status",
          "public_use_status",
          "recommended_uses",
          "scene_tags",
          "sponsorship_items"
        ]
      }
    }
  }
};
